up
YuriiMakoveichuk/project-MobileTeam-1 pull request #4
Opened 2024-03-22 03:03 UTC by Todorak1717

2024-03-22 08:59 UTC, YuriiMakoveichuk requested changes
не прописані шляхи до фото picture не треба так як фотки однакові, треба наприклад <img
                srcset=".img/reviews-img/Ellipse21@2x.jpg 2x"
                src="./img/reviews-img/Ellipse21.jpg"
                alt="Portrait of John Wax"
                width="100"
              />
у назвах фото не треба щоб був пробіл або Ellihse21 або Ellihse-21 або Ellihse_21

2024-03-22 23:38 UTC, Todorak1717 commented
все оновила

2024-03-23 09:08 UTC, YuriiMakoveichuk approved these changes
все добре, але у всіх шляхах до фото треба видилити одну крапку тому що на загальному проекті їх не буде видно. і ще за допомогою srcset фотки @2x зробить

2024-03-23 09:08 UTC, YuriiMakoveichuk requested changes
все добре, але у всіх шляхах до фото треба видилити одну крапку тому що на загальному проекті їх не буде видно. і ще за допомогою srcset фотки @2x зробить

2024-03-23 09:42 UTC, YuriiMakoveichuk approved these changes

2024-03-23 09:42 UTC, merged